name = "fin-flow"
main = "src/index.js"
compatibility_date = "2026-05-20"

[observability.logs]
enabled = true
invocation_logs = true

[durable_objects]
bindings = [
  { name = "COLLECTOR", class_name = "CapitalFlowCollector" }
]

[triggers]
crons = ["* * * * *"]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CapitalFlowCollector"]
