import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join, extname } from "path";

const distDir = join(import.meta.dirname, "..", "dist", "ui", "assets");
const outFile = join(import.meta.dirname, "..", "src", "pages", "ui-build.js");

function escapeTemplateLiterals(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

function escapeInlineScriptContent(str) {
  return str.replace(/<\/script/gi, "<\\\\\\\\/script");
}

function escapeInlineStyleContent(str) {
  return str.replace(/<\/style/gi, "<\\\\\\\\/style");
}

function main() {
  const files = readdirSync(distDir);
  const jsFiles = files.filter((f) => extname(f) === ".js");
  const cssFiles = files.filter((f) => extname(f) === ".css");

  if (jsFiles.length !== 1) {
    throw new Error(`Expected exactly one JS file in dist/ui/assets, found ${jsFiles.length}: ${jsFiles.join(", ")}`);
  }
  if (cssFiles.length !== 1) {
    throw new Error(`Expected exactly one CSS file in dist/ui/assets, found ${cssFiles.length}: ${cssFiles.join(", ")}`);
  }

  const jsContent = escapeInlineScriptContent(readFileSync(join(distDir, jsFiles[0]), "utf-8"));
  const cssContent = escapeInlineStyleContent(readFileSync(join(distDir, cssFiles[0]), "utf-8"));

  const output = `// Auto-generated by scripts/embed-ui.mjs — do not edit manually.
export const UI_CSS = \`${escapeTemplateLiterals(cssContent)}\`;
export const UI_JS = \`${escapeTemplateLiterals(jsContent)}\`;
`;

  writeFileSync(outFile, output, "utf-8");
  console.log(`Generated ${outFile}`);
}

main();
